//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ltht.TechTest.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Colour
    {
        public Colour()
        {
            this.People = new HashSet<Person>();
        }
    
        public int ColourId { get; set; }
        public string Name { get; set; }
        public bool IsEnabled { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
    }
}
